display=":1"

[key-bindings]
close_window = "Mod4-w"
exec_launcher = "Mod4-r"
next_workspace = "Mod4-n"
previous_workspace = "Mod4-p"

[workspace.Main]

[workspace.Chat]

[theme]
border_width = 5
border_color = "#990000"
